package ddl

import (
	"strings"
	"testing"

	"sqlite2pg/internal/config"
)

func TestGenerateCreateTable_RowIDAliasIdentity(t *testing.T) {
	const identity = "GENERATED BY DEFAULT AS IDENTITY"
	tests := []struct {
		name     string
		tc       config.TableConfig
		wantLine string // substring expected on the id column line, or "" for none
	}{
		{
			name: "INTEGER PK with integer target gets identity",
			tc: config.TableConfig{
				ColumnOrder: []string{"id", "n"},
				Columns: map[string]config.ColumnConfig{
					"id": {DeclaredType: "INTEGER", TargetType: "integer", PrimaryKeySeq: 1, NotNull: true},
					"n":  {DeclaredType: "TEXT", TargetType: "text"},
				},
			},
			wantLine: `"id" integer NOT NULL ` + identity,
		},
		{
			name: "lowercase declared type still matches",
			tc: config.TableConfig{
				ColumnOrder: []string{"id"},
				Columns: map[string]config.ColumnConfig{
					"id": {DeclaredType: "integer", TargetType: "bigint", PrimaryKeySeq: 1},
				},
			},
			wantLine: `"id" bigint ` + identity,
		},
		{
			name: "AUTOINCREMENT shares the INTEGER declared type and gets identity",
			tc: config.TableConfig{
				ColumnOrder: []string{"id"},
				Columns: map[string]config.ColumnConfig{
					"id": {DeclaredType: "INTEGER", TargetType: "bigint", PrimaryKeySeq: 1},
				},
			},
			wantLine: `"id" bigint ` + identity,
		},
		{
			name: "INT PK is not a rowid alias",
			tc: config.TableConfig{
				ColumnOrder: []string{"id"},
				Columns: map[string]config.ColumnConfig{
					"id": {DeclaredType: "INT", TargetType: "integer", PrimaryKeySeq: 1},
				},
			},
			wantLine: "",
		},
		{
			name: "composite PK gets no identity",
			tc: config.TableConfig{
				ColumnOrder: []string{"a", "b"},
				Columns: map[string]config.ColumnConfig{
					"a": {DeclaredType: "INTEGER", TargetType: "integer", PrimaryKeySeq: 1},
					"b": {DeclaredType: "INTEGER", TargetType: "integer", PrimaryKeySeq: 2},
				},
			},
			wantLine: "",
		},
		{
			name: "composite PK with dropped second member gets no identity",
			tc: config.TableConfig{
				ColumnOrder: []string{"a", "b"},
				Columns: map[string]config.ColumnConfig{
					"a": {DeclaredType: "INTEGER", TargetType: "integer", PrimaryKeySeq: 1},
					"b": {DeclaredType: "INTEGER", TargetType: DropSentinel, PrimaryKeySeq: 2},
				},
			},
			wantLine: "",
		},
		{
			name: "composite PK with dropped first member gets no identity",
			tc: config.TableConfig{
				ColumnOrder: []string{"a", "b"},
				Columns: map[string]config.ColumnConfig{
					"a": {DeclaredType: "INTEGER", TargetType: DropSentinel, PrimaryKeySeq: 1},
					"b": {DeclaredType: "INTEGER", TargetType: "integer", PrimaryKeySeq: 2},
				},
			},
			wantLine: "",
		},
		{
			name: "INTEGER PK retargeted to uuid gets no identity",
			tc: config.TableConfig{
				ColumnOrder: []string{"id"},
				Columns: map[string]config.ColumnConfig{
					"id": {DeclaredType: "INTEGER", TargetType: "uuid", PrimaryKeySeq: 1},
				},
			},
			wantLine: "",
		},
		{
			name: "non-PK INTEGER column gets no identity",
			tc: config.TableConfig{
				ColumnOrder: []string{"id", "n"},
				Columns: map[string]config.ColumnConfig{
					"id": {DeclaredType: "TEXT", TargetType: "text", PrimaryKeySeq: 1},
					"n":  {DeclaredType: "INTEGER", TargetType: "integer"},
				},
			},
			wantLine: "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ddl, err := GenerateCreateTable("t", tt.tc)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if tt.wantLine == "" {
				if strings.Contains(ddl, identity) {
					t.Errorf("expected no identity clause, got:\n%s", ddl)
				}
				return
			}
			if !strings.Contains(ddl, tt.wantLine) {
				t.Errorf("expected line containing %q, got:\n%s", tt.wantLine, ddl)
			}
		})
	}
}
